version: '2'
services: 
  kafka:
    build: kafka/
    environment:
      # TODO: change advertised host to enumerated host IP
      - ADVERTISED_HOST=10.0.1.15
      - ADVERTISED_PORT=9092
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - network-o-doom
networks:
  network-o-doom:
    driver: bridge
