version: '2'
services: 
  kafka:
    build: kafka/
    environment:
      - LOG_RETENTION_HOURS=1
      - LOG_RETENTION_BYTES=1073741824
      - NUM_PARTITIONS=1
      - DELETE_TOPIC_ENABLE=true
      - ADVERTISED_PORT=9092
    env_file: .env
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - network-o-doom
networks:
  network-o-doom:
    driver: bridge
